name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: azure/docker-login@v1
      with:
        login-server: registry.hub.docker.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t thnkndblv/ariang .
        docker push thnkndblv/ariang
